### PR TITLE
Update/fix apispec and pyyaml, fix poetry 1.0 support

### LINKED ISSUE #32: Support / test newer versions of dependencies
Because the following version constraints are defined:

```
apispec = {version = "^1.0",optional = true}
pyyaml = {version = "^3.13",optional = true}
```

Only `apispec 1.x` and `pyyaml 3.13.x` will be used/tested when `flama[schema]` is installed.

`apispec` is on version 3 and `pyyaml` is at 5 now.  There are numerous useful changes in those projects that can be integrated into `flama`.

### PR DESCRIPTION
**Pull request by uSpike**
Fixes #32

### CODE REVIEW

**Comment by perdy** [comment]
Current version of Flama is not compatible with any Starlette version even if we allow install it, some of the code has a hard dependency on latest version of Starlette.

Regarding apispec 3.0 and pyyaml 5.0: Flama is upgraded to version 0.12 where it's compatible with them.

**Comment by uSpike** [comment]
> the code has a hard dependency on latest version of Starlette.

The `starlette = "^0.12.0"` entry in `pyproject.toml` restricts starlette to `'starlette>=0.12.0,<0.13.0'`.  Look at your generated `setup.py`.  Please consider changing this.

**Comment by uSpike** [comment]
Starlette 0.13.0 is the latest version and is incompatible with the declared dependencies of this project.

**Comment by perdy** [comment]
Good catch, I updated it and release a new version (0.13) that allows to use any Starlette version above 0.12

Thanks!

**Pull request closed without merging**
